# Stage 1
FROM node:18-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm install --only=production
COPY . .

# Stage 2
FROM node:18-alpine
WORKDIR /app

RUN addgroup -S appgrp && adduser -S appusr -G appgrp

COPY --from=builder /app /app

USER appusr

EXPOSE 3000
CMD ["node", "src/index.js"]